// Generated by gencpp from file service/WordCount.msg
// DO NOT EDIT!


#ifndef SERVICE_MESSAGE_WORDCOUNT_H
#define SERVICE_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <service/WordCountRequest.h>
#include <service/WordCountResponse.h>


namespace service
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::service::WordCount&) { return value(); }
};

template<>
struct DataType< ::service::WordCount > {
  static const char* value()
  {
    return "service/WordCount";
  }

  static const char* value(const ::service::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::service::WordCountRequest> should match
// service_traits::MD5Sum< ::service::WordCount >
template<>
struct MD5Sum< ::service::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service::WordCount >::value();
  }
  static const char* value(const ::service::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::WordCountRequest> should match
// service_traits::DataType< ::service::WordCount >
template<>
struct DataType< ::service::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::service::WordCount >::value();
  }
  static const char* value(const ::service::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service::WordCountResponse> should match
// service_traits::MD5Sum< ::service::WordCount >
template<>
struct MD5Sum< ::service::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service::WordCount >::value();
  }
  static const char* value(const ::service::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service::WordCountResponse> should match
// service_traits::DataType< ::service::WordCount >
template<>
struct DataType< ::service::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::service::WordCount >::value();
  }
  static const char* value(const ::service::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_MESSAGE_WORDCOUNT_H
